default_language_version:
  python: python3.10
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-ast
      - id: check-added-large-files
      - id: debug-statements
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args:
          - "--fix=no"
      - id: trailing-whitespace
        args:
          - "--markdown-linebreak-ext=md"
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.10.1'
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        exclude: tests
